services:
  - type: web
    name: TBMW
    env: node
    plan: free
    repo: https://github.com/Yosshy-123/Yoroxy.git
    branch: main
    region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
